### ISSUE TITLE
Output is duplicated

### ISSUE THREAD

**Issue by jamonholmgren** [enquirer/prompt-list#2] opened 2017-02-11 22:39 UTC
Replication repo: https://github.com/jamonholmgren/prompt-list-duplication

Output from list prompt is duplicated:

![image](https://cloud.githubusercontent.com/assets/1479215/22858035/a5962ad6-f067-11e6-9f89-951f7efb27c1.png)

Any ideas why this might be happening?

**Comment by jamonholmgren** [comment] 2017-02-11 22:41
Oops...I forgot to remove a duplicate log in the example. So I haven't replicated this issue.

We are having duplicate output, though, in Ignite. Will continue to investigate.

**Comment by jamonholmgren** [comment] 2017-02-11 22:55
Okay, new commit does show the issue.

![image](https://cloud.githubusercontent.com/assets/1479215/22858168/2b0310f6-f06a-11e6-9cde-e877b34b33c4.png)

**Comment by jonschlinkert** [comment] 2017-02-11 23:24
strange, that definitely shouldn't be happening. I think I might know what's causing that, I'll look into it. thanks for creating the issue

**Comment by doowb** [comment] 2017-02-12 16:03
I think these lines: https://github.com/enquirer/prompt-list/blob/master/index.js#L50-L51
need to use `.only`  instead of `.ui.on`.

And this line: https://github.com/enquirer/prompt-list/blob/master/index.js#L94
should be `this.once('answer', show);`.

Like how it's being done in [prompt-checkbox here](https://github.com/enquirer/prompt-checkbox/blob/master/index.js#L55).

**Comment by jamonholmgren** [comment] 2017-02-13 21:07
@jonschlinkert Thanks for looking into this. Any timeline? I'd rather not merge that PR I linked to above if I can help it, but we're planning on releasing Ignite 2.0.beta in the next few weeks and will need some resolution.

**Comment by jonschlinkert** [comment] 2017-02-13 22:24
> Any timeline?

we can do this pretty quickly. Is tomorrow okay? (today is my b-day :) I'm planning on gorging myself with chocolate cupcakes for a few hours lol)

> we're planning on releasing Ignite 2.0.beta in the next few weeks and will need some resolution.

That's awesome! @doowb's proposed solution is exactly what I was thinking was the cause. We'll let you know as soon as we have a fix

**Comment by doowb** [comment] 2017-02-13 23:31
@jamonholmgren I pushed up the changes for the bug fix (along with some others I found) and published to npm as `0.1.2`.

Thanks for opening this and let us know if you find any more bugs.

**Comment by GantMan** [comment] 2017-02-14 04:25
@jonschlinkert - happy birthday!!!!  We should mail you some stickers.  DM me your address if you want some 👍

**Comment by jamonholmgren** [comment] 2017-02-14 06:27
@jonschlinkert @doowb AWESOME! Please DM @GantMan like he said, we'll send you some swag. You're the best.

**Comment by jonschlinkert** [comment] 2017-02-14 19:45
thanks!

**Comment by jonschlinkert** [comment] 2017-03-06 12:10
closing since this was resolved. @GantMan we'd love some swag, not sure where to DM you, my email address is on my profile if you want to shoot over your contact info, thanks!

**Closed as completed by jonschlinkert** 2017-03-06 12:10 UTC
Labels: bug

**Comment by jamonholmgren** [comment] 2017-05-18 06:58
@jonschlinkert Just saw this...swag will be forthcoming...

**Comment by jonschlinkert** [comment] 2017-05-18 11:36
no worries! thank you
